### ISSUE TITLE
allow default substatments for leaf-list

### ISSUE THREAD

**Issue by hellt** [openconfig/goyang#136]
Currently its not allowed, as it is not present in YANG 1.0 RFC,
YANG 1.1 adds `default` substatement to leaf-lists

**Comment by robshakir** [comment]
Thanks for reporting this, I think this is a relatively simple change -- through adding `Default` to the `LeafList` node type ([here](https://github.com/openconfig/goyang/blob/master/pkg/yang/yang.go#L417)), and adding testing. I'd be happy to review a PR or provide further guidance if this is something that you'd like to contribute -- otherwise, we can add this to the backlog of feature requests.

Contents of a default are just populated into a string, so we'd expect downstream consumers to be able to figure out what this means (as we do today for leaves, since there's ambiguity sometimes -- e.g.,:

```yang

leaf a {
  type union {
    type string { pattern "a.*"; }
    type string { pattern "b.*"; }
  }
}
```

Here we'd need to understand the contents of the YangTypes, which `pkg/yang` does not intend to do.

r.

**Comment by hellt** [comment]
@robshakir I have added a PR (#139) where I try to address this
