### ISSUE TITLE
(*yang.Entry).Modules()/Find("/validpath/...") panics

### ISSUE THREAD

**Issue by gsindigi** [openconfig/goyang#97]
1. (*yang.Entry).Modules() - panics even for the valid node entries
2. (*yang.Entry).Find() - panics when the path begins with "/"

Both above cases, type assertion `e.Node.(*Module)` results in panic  
```go panic: interface conversion: yang.Node is nil, not *yang.Module ``` 

Below is a test code, the schema is generated using openconfig-interfaces.yang file; 
```go
    deviceEntry, ok := openconfig.SchemaTree["Device"]
    assert.True(t, ok, "DeviceEntry should be present")
    assert.NotNil(t, deviceEntry, "DeviceEntry should be non-nil")

    interfaces := deviceEntry.Find("interfaces")
    assert.NotNil(t, interfaces, "interfaces should be non-nil")

    //	modules := interfaces.Modules()  // <-- panics here - e.Node.(*Module).modules
    //	assert.NotNil(t, modules, "modules should be non-nil")

    interfaces = deviceEntry.Find("/interfaces") // <-- panics here - e.Node.(*Module).GetPrefix():
    assert.NotNil(t, interfaces, "interfaces should be non-nil")

```
Are both cases above valid ?  Is there any other way to find the module for an yang.Entry?

**Comment by robshakir** [comment]
If you are using generated code from ygot, then the methods that are provided in goyang will not be safe - because we don't store the entire tree in the generated code (the schematree is a partial reflection of the entries). Anything related to the Node field isn't actually populated.

It'd be useful to understand what you're trying to achieve from the ygot perspective, and we can then determine how to best provide that information.

**Comment by gsindigi** [comment]
Yes, its generated code from `ygot`.   Is there any way to know which of such methods are safe or otherwise?

**Comment by wenovus** [comment]
See openconfig/ygot#489
